### ISSUE TITLE
Warping to new canal map is broken

### ISSUE THREAD

**Issue by idermailer** [hdtf-owf/hdtf_issues#370]
### Expected Behavior

When I see cutscene a1c2p3s1, then player should be in elevator.

### Steps to Reproduce

1. Load a map before a1c3p1_canal. If you load a1c3p1_canal directly or start new game from "TRUST", this bug will NOT happen.
2. Play game until cutscene a1c2p3s1 is shown.
3. The cutscene and timer end, then you are placed at wrong location.

### Detailed Description

![a1c3p1_canal0003](https://github.com/hdtf-owf/hdtf_issues/assets/85840398/f3e43cc6-fd1d-4f97-a590-c9faf51bfa6d)
The wrong coordinate is -4 x, -4 y, 89 z.
And when stare some direction, "Material models/props_unique/reflectivity_50b does not support vertex format used by the mesh (maybe missing fields or mismatched vertex compression?), mesh will not be rendered. Grab a programmer!" is repeatably logged.

### Operating System

Windows 10 64bit

**Comment by Terrrors** [comment]
That's because the updated office map wasn't pushed, since I'm still working on the map. I updated the level transitions between office, canal and urban. But because the outdated version of office is still using the old level transition map logic, the level transition isn't going to work correctly.

So this'll be fixed once I've pushed the updated office map.
